---
apiVersion: v1
kind: Namespace
metadata:
  name: vf-test6
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vf-test1
  namespace: vf-test6
spec:
  config: |-
    {
        "cniVersion": "1.0.0",
        "name": "vf-test1",
        "type": "sriov",
        "vlan": 0,
        "spoofchk": "on",
        "trust": "on",
        "vlanQoS": 0,
        "logLevel": "info",
        "ipam": {
            "type": "host-local",
            "ranges": [
                [
                    {
                        "subnet": "10.0.2.0/24"
                    }
                ]
            ]
        }
    }
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: vf-test6
  name: vf-test6
spec:
  spec:
    devices:
      requests:
      - name: vf
        exactly:
          deviceClassName: sriovnetwork.openshift.io
      config:
      - requests: ["vf"]
        opaque:
          driver: sriovnetwork.openshift.io
          parameters:
            apiVersion: sriovnetwork.openshift.io/v1alpha1
            kind: VfConfig
            ifName: net1
            netAttachDefName: vf-test1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vf-test6
  name: pod0
  labels:
    app: pod0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod0
  template:
    metadata:
      labels:
        app: pod0
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: ctr0
        image: quay.io/schseba/toolbox:latest
        command:
          - /bin/bash
          - -c
          - sleep INF
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
        resources:
          claims:
          - name: vf
      resourceClaims:
      - name: vf
        resourceClaimTemplateName: vf-test6
